### ISSUE TITLE
Advanced settings: IMAP Port "143" with IMAP Security "Automatic" fails at first attempt

### ISSUE THREAD

**Issue by gerryfrancis** [deltachat/deltachat-desktop#1296]
**- Platform (linux/mac/windows):**
Windows 8.1 Pro (x64).

**- Delta Chat Desktop Version:**
0.901.0.

**- Expected behavior:**
First login (initial configuration) of Delta Chat (with advanced settings) is successful.

**- Actual behavior:**
First login (initial configuration) of Delta Chat (with advanced settings) fails. (Message: "Response from posteo.de:143: other os error Some providers place additional information in your inbox; you can check them it eg. in the web frontend. Consult your provider or friends if you run into problems.") (I really dought that this response is from Posteo.)

**- Workaround:**
"Fool" Delta Chat by changing the account name temporarily from "[...]@posteo.at" to "[...]@posteo.de" and back, then press the "Login" button again.

**- Remark(s):**
Delta Chat has been installed from scratch and a new profile has been created.
The account username differs from the IMAP- and the SMTP username ("[...]@posteo.at" instead of "[...]@posteo.de"), because I have to use an _alias_ mail address, and Posteo does not allow a login with an alias.

**Comment by Jikstra** [comment]
> "Fool" Delta Chat by changing the account name temporarily from "[...]@posteo.at" to "[...]@posteo.de" and back, then press the "Login" button again.

This shouldn't fool delta chat. Is it possible that the first try just didn't work? Pressing login will just retry a new login.

**Comment by gerryfrancis** [comment]
> Is it possible that the first try just didn't work?

@Jikstra It did not work because of Delta Chat. I performed this routine twice to check whether I made a typo or not, but it is reproducible. Maybe I can find a neat utility to make a small animation/video about it.

> I have a posteo account so can give it a try

That is great! Here is a help article on how to add (or remove) an email alias at Posteo: https://posteo.de/en/help/how-do-i-add-or-delete-an-email-alias

Thank you so much in advance for your support!

**Comment by Simon-Laux** [comment]
> Maybe I can find a neat utility to make a small animation/video about it.

Try https://github.com/phw/peek

**Comment by gerryfrancis** [comment]
Thanks @Simon-Laux for your recommendation, I had been working on the video with another editor, so I will come back to your advice next time. I hope the video can be viewed well:

![delta_chat](https://user-images.githubusercontent.com/51095533/71833680-c1602300-30ad-11ea-8405-18edfa9c94b9.gif)

Note: No contact requests are offered, neither right after the configuration procedure, nor after closing and starting Delta Chat again. It seems that the mail alias breaks something important in between.

**Comment by gerryfrancis** [comment]
Here is the corresponding part from the Delta Chat log file:

`"2020-01-04T20:06:21.125Z"	"main/index"	"INFO"		"cwd C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat"
"2020-01-04T20:06:21.203Z"	"main/menu"	"INFO"		"rebuilding menu with locale en"
"2020-01-04T20:06:23.235Z"	"main/state"	"INFO"		"Saving state to C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\config.json"
"2020-01-04T20:06:27.367Z"	"main/state"	"INFO"		"Saving state to C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\config.json"
"2020-01-04T20:06:30.586Z"	"main/state"	"INFO"		"Saving state to C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\config.json"
"2020-01-04T20:07:15.371Z"	"main/deltachat/login"	"INFO"		"Using deltachat instance C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\67657272795f6640706f7374656f2e6174"
"2020-01-04T20:07:20.910Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(5) src\\job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-01-04T20:07:20.912Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(5) src\\job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-01-04T20:07:20.913Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(8) src\\job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-01-04T20:07:20.914Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(8) src\\job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-01-04T20:07:20.915Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(9) src\\job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-01-04T20:07:20.916Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(9) src\\job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-01-04T20:07:20.917Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(5) src\\job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-01-04T20:07:20.918Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(5) src\\job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-01-04T20:07:20.919Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(5) src\\job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-01-04T20:07:20.919Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(5) src\\job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-01-04T20:07:20.921Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(9) src\\job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-01-04T20:07:20.921Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(9) src\\job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-01-04T20:07:20.922Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(9) src\\job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-01-04T20:07:20.923Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(9) src\\job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-01-04T20:07:20.925Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(8) src\\job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-01-04T20:07:20.926Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(8) src\\job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-01-04T20:07:20.927Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(8) src\\job_thread.rs:90: connect+fetch failed: \"IMAP Connect without configured params\", reconnect & retry"
"2020-01-04T20:07:20.928Z"	"main/deltachat"	"WARNING"	"\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:240:11),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:777:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"ThreadId(8) src\\job_thread.rs:93: connect+fetch failed: \"IMAP Connect without configured params\""
"2020-01-04T20:07:21.725Z"	"main/deltachat"	"ERROR"	"\nonError (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:245:11),\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:253:7),\nDeltaChat.emit (events.js:182:13),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:783:12),\nDeltaChat.binding.dcn_set_event_handler (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:35:7)"	"Response from posteo.de:143: other os error\n\nSome providers place additional information in your inbox; you can check them it eg. in the web frontend. Consult your provider or friends if you run into problems."
"2020-01-04T20:07:21.725Z"	"main/deltachat/login"	"INFO"		"Logged out"
"2020-01-04T20:07:21.730Z"	"renderer/ipc"	"ERROR"	"\nEventEmitter.ipcBackend.on.args (file:///C:/Users/PC_USER/AppData/Local/Programs/deltachat-desktop/resources/app.asar/static/bundle.js:117678:46),\nEventEmitter.emit (events.js:187:15)"	"Response from posteo.de:143: other os error\n\nSome providers place additional information in your inbox; you can check them it eg. in the web frontend. Consult your provider or friends if you run into problems."
"2020-01-04T20:07:22.727Z"	"main/state"	"INFO"		"Saving state to C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\config.json"
"2020-01-04T20:07:35.012Z"	"main/deltachat/login"	"INFO"		"Using deltachat instance C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\67657272795f6640706f7374656f2e6174"
"2020-01-04T20:07:35.034Z"	"main/deltachat/login"	"INFO"		"Ready"
"2020-01-04T20:07:35.052Z"	"main/deltachat/login"	"INFO"		"dc_get_info"	{"mdns_enabled":"1","database_dir":"C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\67657272795f6640706f7374656f2e6174\\db.sqlite","display_name":"0","fingerprint":"6DFA12B127740364DD036D44D93F9294D9D4B749","e2ee_enabled":"1","entered_account_settings":"anonymized@posteo.at imap:anonymized@posteo.de:***:posteo.de:143:cert_automatic smtp:anonymized@posteo.de:***:posteo.de:587:cert_automatic 0","level":"awesome","folders_configured":"3","database_version":"61","mvbox_move":"1","public_key_count":"0","number_of_contacts":"0","sqlite_version":"3.29.0","inbox_watch":"1","used_account_settings":"anonymized@posteo.at imap:anonymized@posteo.de:***:posteo.de:143:cert_automatic smtp:anonymized@posteo.de:***:posteo.de:587:cert_automatic AUTH_NORMAL 0x4IMAP_STARTTLS 0x100SMTP_STARTTLS 0x10000","configured_mvbox_folder":"DeltaChat","bcc_self":"0","number_of_chats":"0","sqlite_thread_safe":"1","deltachat_core_version":"v1.0.0-beta.21","configured_sentbox_folder":"Sent","blobdir":"C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\67657272795f6640706f7374656f2e6174\\db.sqlite-blobs","sentbox_watch":"1","arch":"64","mvbox_watch":"1","selfavatar":"<unset>","number_of_chat_messages":"0","is_configured":"1","private_key_count":"1","messages_in_contact_requests":"0"}
"2020-01-04T20:07:35.970Z"	"localize"	"ERROR"	"\nApp.getMessage [as translate] (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\localize.js:15:11),\ntranslate (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:188:16),\nDCChatList.__chatSubtitle (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:165:18),\nDCChatList.getFullChatById (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:138:22),\nDCChatList.onChatModified (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:30:23),\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:218:21),\nDeltaChat.emit (events.js:187:15),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:792:12)"	"Missing translation for key 'device_talk_subtitle'"
"2020-01-04T20:07:35.980Z"	"localize"	"ERROR"	"\nApp.getMessage [as translate] (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\localize.js:15:11),\ntranslate (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:188:16),\nDCChatList.__chatSubtitle (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:165:18),\nDCChatList.getFullChatById (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:138:22),\nDCChatList.onChatModified (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:30:23),\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:218:21),\nDeltaChat.emit (events.js:187:15),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:792:12)"	"Missing translation for key 'device_talk_subtitle'"
"2020-01-04T20:07:35.986Z"	"localize"	"ERROR"	"\nApp.getMessage [as translate] (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\localize.js:15:11),\ntranslate (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:188:16),\nDCChatList.__chatSubtitle (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:165:18),\nDCChatList.getFullChatById (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:138:22),\nDCChatList.onChatModified (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:30:23),\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:218:21),\nDeltaChat.emit (events.js:187:15),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:792:12)"	"Missing translation for key 'device_talk_subtitle'"
"2020-01-04T20:07:35.991Z"	"localize"	"ERROR"	"\nApp.getMessage [as translate] (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\localize.js:15:11),\ntranslate (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:188:16),\nDCChatList.__chatSubtitle (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:165:18),\nDCChatList.getFullChatById (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:138:22),\nDCChatList.onChatModified (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\chatlist.js:30:23),\nDeltaChat.dc.on (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\src\\main\\deltachat\\controller.js:218:21),\nDeltaChat.emit (events.js:187:15),\nhandleEvent (C:\\Users\\PC_USER\\AppData\\Local\\Programs\\deltachat-desktop\\resources\\app.asar\\node_modules\\deltachat-node\\lib\\deltachat.js:792:12)"	"Missing translation for key 'device_talk_subtitle'"
"2020-01-04T20:07:36.035Z"	"main/state"	"INFO"		"Saving state to C:\\Users\\PC_USER\\AppData\\Local\\DeltaChat\\config.json"`

(partly anonymized, which is the reason why it took a bit longer...)

**Comment by gerryfrancis** [comment]
Hey, I have found out that initial configuration with a mail alias is successful when IMAP and SMTP security are explicitly set to "STARTTLS".

Nevertheless, the former behavior described is a bug anyway, because automatic detection does not work, and Delta Chat is in a state where contact requests are not functioning.

**Comment by pabzm** [comment]
I tested some variants with a similar setup (alias@posteo.at) and found that setting the IMAP-Port to 143 appears to be the problem. If you don't change that field, the login works at the first attempt.

So apparently automatically figuring out that Port 143 requires STARTTLS is broken.

**Comment by gerryfrancis** [comment]
Thanks a lot, @pabzm !

> setting the IMAP-Port to 143 appears to be the problem. If you don't change that field, the login works at the first attempt.

Maybe the user must not edit the field when automatic detection is chosen?

**Comment by gerryfrancis** [comment]
Still an issue in version 0.999.1.

**Comment by nicodh** [comment]
@gerryfrancis can you please test again? We fixed some issues in current master...

**Comment by gerryfrancis** [comment]
@nicodh Tested with deltachat-desktop-1466.exe, now the error message is different, but the issue remains:

![grafik](https://user-images.githubusercontent.com/51095533/74853030-a4ba3a80-533d-11ea-8171-2ac95cc33bb1.png)

**Comment by nicodh** [comment]
To analyze this I think we need a kind of matrix with a list of (valid) advanced settings which will fail.
I know that setting only the mail port but not the mail_server will fail. So it seems port 143 with STARTTLS also fails.
The relevant part is https://github.com/deltachat/deltachat-core-rust/blob/master/src/configure/mod.rs#L266

**Comment by gerryfrancis** [comment]
> So it seems port 143 with STARTTLS also fails.

@nicodh To clarify, I did not select "STARTTLS", the setting was "Automatic", I just entered port 143.

**Comment by gerryfrancis** [comment]
Version 1.0.0 is affected, too.

**Comment by gerryfrancis** [comment]
Version 1.1.0 is affected, too.

**Comment by gerryfrancis** [comment]
Version 1.2.0 is affected, too.

**Comment by gerryfrancis** [comment]
Version 1.3.0 does not work with automatic settings either, but now I get a different error message:

![grafik](https://user-images.githubusercontent.com/51095533/81112415-e7dc8080-8f1e-11ea-8e9d-423e424dfbed.png)

**Comment by Jikstra** [comment]
Is this happening on android too?

**Comment by gerryfrancis** [comment]
@Jikstra I cannot test on Android for now, sorry. Will try to do this in a couple of days.

**Comment by gerryfrancis** [comment]
I was not able to test on Android, yet, but since Desktop version 1.3.4 I get the same message as described in https://github.com/deltachat/deltachat-desktop/issues/1296#issuecomment-588312337 again.

**Comment by Jikstra** [comment]
weird i tried my posteo.net address with the 1.3.4 yesterday and it worked seemless (didn't have to change any advanced settings). Maybe it's about the posteo.de? But would be weird if they have different settings for the different domains..

**Comment by gerryfrancis** [comment]
@Jikstra I guess it is because of my mail alias (with the domain posteo.**at**). (You may want to see the video in https://github.com/deltachat/deltachat-desktop/issues/1296#issuecomment-571221531 .)

**Comment by gerryfrancis** [comment]
Hey, I have retested in the new version 1.4.2 and it works now, thanks a lot! :+1:

However, when I enter my alias address (ending with "@posteo.at"), SSL is used instead of STARTTLS. I will close here and file a new issue for that.

Again, many thanks to all people involved here!
