### ISSUE TITLE
camera stays sometimes on after qr code scan

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#1730]
This is not the expected behavior. The camera should turn itself of always after an qr code scan.
I saw this issue on linux and on mac, so it's likely on windows, too.

**Comment by Jikstra** [comment]
I think it got solved by the overhaul, please reopen if it happens again

**Comment by Simon-Laux** [comment]
still happens sometimes, I think we should take this in our own hands and build our own qr code reader component, also to solve #2634

**Comment by r10s** [comment]
ftr, i cannot reproduce the issue and have not seen the described behaviour for years. was just trying hard to reproduce it on macos ventura, without success 👍 - is there a way to trigger the behaviour? is it about the welcome-screen or the in-app scanner?

**Comment by r10s** [comment]
it happens to me as well now and i found a way to reproduce it on macos: it happens reproducible when you close the scanner dialog _before_ the camera is initialized (so, before the camera image is shown). 

maybe just a a forgotten deinit and no funamental issue with the scanner in use.

https://user-images.githubusercontent.com/9800740/233804598-86c8bd91-24ac-4f51-b49e-076878729050.MOV

**Comment by Simon-Laux** [comment]
still an issue as of #3507
